export const SEARCH_FOCUS = 'header/Search_Focused'
export const SEARCH_BLUR = 'header/Search_Blur'
export const CHANGE_LIST = 'header/ChangeList'
export const MOUSE_ENTER = 'header/MouseEnter'
export const MOUSE_LEAVE = 'header/MouseLeave'
export const CHANGE_PAGE = 'header/ChangePage'